# Generated by Django 4.2.2 on 2023-06-06 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_game_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1)], verbose_name='Max Level'),
        ),
    ]
