# Generated by Django 4.2.1 on 2023-06-01 20:24

from django.db import migrations, models
import my_plant_app.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=20, validators=[my_plant_app.web.validators.start_with_capital_letter_validator], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=20, validators=[my_plant_app.web.validators.start_with_capital_letter_validator], verbose_name='Last Name'),
        ),
    ]
